apiVersion: v1
kind: PersistentVolume
metadata:
  name: python-logs-pv
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/python-logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: python-sources-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /mnt/data/python-sources
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-sources-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi